name: coverage

on: ['push', 'pull_request']

jobs:
    test:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.5
                  extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, xdebug
                  coverage: xdebug

            - name: Install dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction
            - name: Execute tests
              run: composer coverage
