name: rector

on: ['push', 'pull_request']

jobs:
    rector:
        runs-on: ubuntu-latest

        name: Rector

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.5
                    extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install dependencies
                run: composer install

            -   name: Rector
                run: composer rector
