name: style

on:
    push:
        branches:
            - main
jobs:
    style:
        name: Style
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.3
                    extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                    coverage: none

            -   name: Install dependencies
                run: composer install

            -   name: Style
                run: composer fix-style

            -   name: Commit Changes
                uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: Fix styling changes
